/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppLayoutImport } from './routes/_app/_layout'
import { Route as AppLayoutSeedPhraseIndexImport } from './routes/_app/_layout/seed-phrase/index'
import { Route as AppLayoutRegistrationPinIndexImport } from './routes/_app/_layout/registration-pin/index'
import { Route as AppLayoutPhoneIndexImport } from './routes/_app/_layout/phone/index'
import { Route as AppLayoutPhoneCodeIndexImport } from './routes/_app/_layout/phone-code/index'
import { Route as AppLayoutLoginIndexImport } from './routes/_app/_layout/login/index'
import { Route as AppLayoutHomeIndexImport } from './routes/_app/_layout/home/index'
import { Route as AppLayoutForgotIndexImport } from './routes/_app/_layout/forgot/index'
import { Route as AppLayoutSeedPhrasePinIndexImport } from './routes/_app/_layout/seed-phrase/pin/index'
import { Route as AppLayoutForgotNewPinIndexImport } from './routes/_app/_layout/forgot/new-pin/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_app/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutSeedPhraseIndexRoute = AppLayoutSeedPhraseIndexImport.update({
  path: '/seed-phrase/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutRegistrationPinIndexRoute =
  AppLayoutRegistrationPinIndexImport.update({
    path: '/registration-pin/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutPhoneIndexRoute = AppLayoutPhoneIndexImport.update({
  path: '/phone/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutPhoneCodeIndexRoute = AppLayoutPhoneCodeIndexImport.update({
  path: '/phone-code/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutLoginIndexRoute = AppLayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutHomeIndexRoute = AppLayoutHomeIndexImport.update({
  path: '/home/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutForgotIndexRoute = AppLayoutForgotIndexImport.update({
  path: '/forgot/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutSeedPhrasePinIndexRoute =
  AppLayoutSeedPhrasePinIndexImport.update({
    path: '/seed-phrase/pin/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutForgotNewPinIndexRoute = AppLayoutForgotNewPinIndexImport.update(
  {
    path: '/forgot/new-pin/',
    getParentRoute: () => AppLayoutRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/_layout': {
      id: '/_app/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_app/_layout/forgot/': {
      id: '/_app/_layout/forgot/'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof AppLayoutForgotIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/home/': {
      id: '/_app/_layout/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppLayoutHomeIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/login/': {
      id: '/_app/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLayoutLoginIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/phone-code/': {
      id: '/_app/_layout/phone-code/'
      path: '/phone-code'
      fullPath: '/phone-code'
      preLoaderRoute: typeof AppLayoutPhoneCodeIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/phone/': {
      id: '/_app/_layout/phone/'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof AppLayoutPhoneIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/registration-pin/': {
      id: '/_app/_layout/registration-pin/'
      path: '/registration-pin'
      fullPath: '/registration-pin'
      preLoaderRoute: typeof AppLayoutRegistrationPinIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/seed-phrase/': {
      id: '/_app/_layout/seed-phrase/'
      path: '/seed-phrase'
      fullPath: '/seed-phrase'
      preLoaderRoute: typeof AppLayoutSeedPhraseIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/forgot/new-pin/': {
      id: '/_app/_layout/forgot/new-pin/'
      path: '/forgot/new-pin'
      fullPath: '/forgot/new-pin'
      preLoaderRoute: typeof AppLayoutForgotNewPinIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/seed-phrase/pin/': {
      id: '/_app/_layout/seed-phrase/pin/'
      path: '/seed-phrase/pin'
      fullPath: '/seed-phrase/pin'
      preLoaderRoute: typeof AppLayoutSeedPhrasePinIndexImport
      parentRoute: typeof AppLayoutImport
    }
  }
}

// Create and export the route tree

interface AppLayoutRouteChildren {
  AppLayoutForgotIndexRoute: typeof AppLayoutForgotIndexRoute
  AppLayoutHomeIndexRoute: typeof AppLayoutHomeIndexRoute
  AppLayoutLoginIndexRoute: typeof AppLayoutLoginIndexRoute
  AppLayoutPhoneCodeIndexRoute: typeof AppLayoutPhoneCodeIndexRoute
  AppLayoutPhoneIndexRoute: typeof AppLayoutPhoneIndexRoute
  AppLayoutRegistrationPinIndexRoute: typeof AppLayoutRegistrationPinIndexRoute
  AppLayoutSeedPhraseIndexRoute: typeof AppLayoutSeedPhraseIndexRoute
  AppLayoutForgotNewPinIndexRoute: typeof AppLayoutForgotNewPinIndexRoute
  AppLayoutSeedPhrasePinIndexRoute: typeof AppLayoutSeedPhrasePinIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutForgotIndexRoute: AppLayoutForgotIndexRoute,
  AppLayoutHomeIndexRoute: AppLayoutHomeIndexRoute,
  AppLayoutLoginIndexRoute: AppLayoutLoginIndexRoute,
  AppLayoutPhoneCodeIndexRoute: AppLayoutPhoneCodeIndexRoute,
  AppLayoutPhoneIndexRoute: AppLayoutPhoneIndexRoute,
  AppLayoutRegistrationPinIndexRoute: AppLayoutRegistrationPinIndexRoute,
  AppLayoutSeedPhraseIndexRoute: AppLayoutSeedPhraseIndexRoute,
  AppLayoutForgotNewPinIndexRoute: AppLayoutForgotNewPinIndexRoute,
  AppLayoutSeedPhrasePinIndexRoute: AppLayoutSeedPhrasePinIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof AppLayoutRouteWithChildren
  '/forgot': typeof AppLayoutForgotIndexRoute
  '/home': typeof AppLayoutHomeIndexRoute
  '/login': typeof AppLayoutLoginIndexRoute
  '/phone-code': typeof AppLayoutPhoneCodeIndexRoute
  '/phone': typeof AppLayoutPhoneIndexRoute
  '/registration-pin': typeof AppLayoutRegistrationPinIndexRoute
  '/seed-phrase': typeof AppLayoutSeedPhraseIndexRoute
  '/forgot/new-pin': typeof AppLayoutForgotNewPinIndexRoute
  '/seed-phrase/pin': typeof AppLayoutSeedPhrasePinIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof AppLayoutRouteWithChildren
  '/forgot': typeof AppLayoutForgotIndexRoute
  '/home': typeof AppLayoutHomeIndexRoute
  '/login': typeof AppLayoutLoginIndexRoute
  '/phone-code': typeof AppLayoutPhoneCodeIndexRoute
  '/phone': typeof AppLayoutPhoneIndexRoute
  '/registration-pin': typeof AppLayoutRegistrationPinIndexRoute
  '/seed-phrase': typeof AppLayoutSeedPhraseIndexRoute
  '/forgot/new-pin': typeof AppLayoutForgotNewPinIndexRoute
  '/seed-phrase/pin': typeof AppLayoutSeedPhrasePinIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_app/_layout': typeof AppLayoutRouteWithChildren
  '/_app/_layout/forgot/': typeof AppLayoutForgotIndexRoute
  '/_app/_layout/home/': typeof AppLayoutHomeIndexRoute
  '/_app/_layout/login/': typeof AppLayoutLoginIndexRoute
  '/_app/_layout/phone-code/': typeof AppLayoutPhoneCodeIndexRoute
  '/_app/_layout/phone/': typeof AppLayoutPhoneIndexRoute
  '/_app/_layout/registration-pin/': typeof AppLayoutRegistrationPinIndexRoute
  '/_app/_layout/seed-phrase/': typeof AppLayoutSeedPhraseIndexRoute
  '/_app/_layout/forgot/new-pin/': typeof AppLayoutForgotNewPinIndexRoute
  '/_app/_layout/seed-phrase/pin/': typeof AppLayoutSeedPhrasePinIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot'
    | '/home'
    | '/login'
    | '/phone-code'
    | '/phone'
    | '/registration-pin'
    | '/seed-phrase'
    | '/forgot/new-pin'
    | '/seed-phrase/pin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/forgot'
    | '/home'
    | '/login'
    | '/phone-code'
    | '/phone'
    | '/registration-pin'
    | '/seed-phrase'
    | '/forgot/new-pin'
    | '/seed-phrase/pin'
  id:
    | '__root__'
    | '/'
    | '/_app/_layout'
    | '/_app/_layout/forgot/'
    | '/_app/_layout/home/'
    | '/_app/_layout/login/'
    | '/_app/_layout/phone-code/'
    | '/_app/_layout/phone/'
    | '/_app/_layout/registration-pin/'
    | '/_app/_layout/seed-phrase/'
    | '/_app/_layout/forgot/new-pin/'
    | '/_app/_layout/seed-phrase/pin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app/_layout"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_app/_layout": {
      "filePath": "_app/_layout.tsx",
      "children": [
        "/_app/_layout/forgot/",
        "/_app/_layout/home/",
        "/_app/_layout/login/",
        "/_app/_layout/phone-code/",
        "/_app/_layout/phone/",
        "/_app/_layout/registration-pin/",
        "/_app/_layout/seed-phrase/",
        "/_app/_layout/forgot/new-pin/",
        "/_app/_layout/seed-phrase/pin/"
      ]
    },
    "/_app/_layout/forgot/": {
      "filePath": "_app/_layout/forgot/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/home/": {
      "filePath": "_app/_layout/home/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/login/": {
      "filePath": "_app/_layout/login/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/phone-code/": {
      "filePath": "_app/_layout/phone-code/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/phone/": {
      "filePath": "_app/_layout/phone/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/registration-pin/": {
      "filePath": "_app/_layout/registration-pin/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/seed-phrase/": {
      "filePath": "_app/_layout/seed-phrase/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/forgot/new-pin/": {
      "filePath": "_app/_layout/forgot/new-pin/index.tsx",
      "parent": "/_app/_layout"
    },
    "/_app/_layout/seed-phrase/pin/": {
      "filePath": "_app/_layout/seed-phrase/pin/index.tsx",
      "parent": "/_app/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
